sudo: false

language: cpp

os:
  - linux
  - osx

compiler:
  - gcc
  - clang

cache:
  - ccache

env:
  - THREADING="serial"
  - THREADING="openmp"
  - THREADING="pthread"

# Apple GCC does not support OpenMP.  GCC with OpenMP requires Homebrew.
# Apple Clang does not support OpenMP.  Clang with OpenMP requires Homebrew.
matrix:
  exclude:
    - os: osx
      env: THREADING="openmp"
    - os: osx
      compiler: gcc

before_script:
  - if [[ ${TRAVIS_OS_NAME} == "osx" ]]; then
      brew update;
      export HOMEBREW_NO_AUTO_UPDATE=1;
      brew ls --versions ccache   > /dev/null || brew install ccache;
      export PATH=/usr/local/opt/ccache/libexec:$PATH;
    fi
  - ccache -z

script:
  - export OMP_NUM_THREADS=2
  - export OMP_PLACES=threads
  - export OMP_PROC_BIND=spread
  # LD_LIBRARY_PATH workaround to find clang's libomp: https://github.com/travis-ci/travis-ci/issues/8613 
  - if [[ ${CC} = clang ]]; then export LD_LIBRARY_PATH=/usr/local/clang/lib${LD_LIBRARY_PATH:+:}$LD_LIBRARY_PATH; fi 
  - mkdir build
  - cd build
  - ../generate_makefile.bash --compiler=$CXX --with-$THREADING --with-options=compiler_warnings
  - make KOKKOS_INTERNAL_GCC_TOOLCHAIN=/usr
  - make test KOKKOS_INTERNAL_GCC_TOOLCHAIN=/usr

after_success:
  - ccache -s
